baseURL = 'https://blazejhanzel.github.io/blazedev-games-hugo/'
languageCode = 'en-us'
title = 'blazeDev Games'
theme = "hugo-coder"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "BÅ‚aÅ¼ej Hanzel"
description = "Providing the feeling of old retro games using the latest technology"
keywords = "games,developer,gamedev"
info = ["26 years old Indie Game Developer from Poland ğŸ‡µğŸ‡± Creator of â€œAstro Strike â€“ Space Shooterâ€ game ğŸ‘¾ and â€œBlaze Builder â€“ Easy Multiplatform Buildâ€ Unity tool ğŸ® I create cool game dev-related projects ğŸ’» and YouTube videos ğŸ¬ I like emojis ğŸ˜„",
  "I started my game development journey when I was 13 years old, take a part of first game dev workshop two years later, created some projects which stay sealed and finally decided to release my own game ğŸ¥³",
  "Iâ€™m documenting my journey on Twitter/X and on YouTube, where I post everything related with game development â€“ devlogs, tips and tutorials."]
avatarURL = "images/avatar.png"
dateFormat = "2 January 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
colorScheme = "dark"
hideColorSchemeToggle = true
maxSeeAlsoItems = 5
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
# Custom remote JS files
customRemoteJS = []

[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 1
url = "https://youtube.com/@blazeDev_vlog"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 2
url = "https://bsky.app/profile/blazedev.games"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 3
url = "https://github.com/blazejhanzel/"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
